# Site settings
author: Brendan Borgers
title: Flatiron School Blog
header-img: img/home-bg.png
email: brendanborgers@gmail.com
copyright_name: Brendan Borgers
description: > # this means to ignore newlines until "baseurl:"
  Blogging through my Flatiron  experience
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  brendanrb

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
